### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by lcl-git-3d** [princeton-vl/Coupled-Iterative-Refinement#10]
Hi,
        When I ran "python additional_scripts/download_datasets.py --bop_dataset ycbv --models ycbv" to download the dataset for training, the program reported an error: urllib.error.HTTPError: HTTPError 403: Forbidden. 
        Then when I'm in the Google browser open this web page "http://ptak.felk.cvut.cz/6DB/public/bop_datasets/", The web page prompts me "You don't have permission to access /6DB/public/bop_datasets/ on this server." How can I solve the problem?

**Comment by lahavlipson** [comment]
Fixed, I didn't realize the URL changed recently.
