### ISSUE TITLE
undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv“

### ISSUE THREAD

**Issue by lcl-git-3d** [princeton-vl/Coupled-Iterative-Refinement#12]
Hi,
When I run: "python train.py --dataset lmo --batch_size 12 --num_inner_loops 10 --num_solver_steps 3". Program error: "ImportError: / home/ta/anaconda3 / envs/cir/lib/python3.8 / site - packages/lietorch_backends retaining - 38 - x86_64 - Linux - gnu. So: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv“

My virtual environment: python=3.8 pytorch=1.8.1 torchvision=0.9.1 cuda=11.1. Both are the same as environment.ymal. 
How can I solve it?

**Comment by ji-min-song** [comment]
Hello,
I have a same problem in RTX 4090.
But it was not in RTX 3090 ti in previous experience.
How about your HW setup?

p.s. It looks like **CUDA error** because when i setup anaconda environment with this github repo instruction. pytorch or torchvision was installed as cpu version.
![image](https://github.com/princeton-vl/Coupled-Iterative-Refinement/assets/80804530/0bc0ff8b-1186-4c6e-82c9-9a1c47c12cbb)

**Comment by lcl-git-3d** [comment]
> Hello, I have a same problem in RTX 4090. But it was not in RTX 3090 ti in previous experience. How about your HW setup?

RTX 3090 CUDA Vision:11.6.Can you solve this problem?

**Comment by ji-min-song** [comment]
i think you have to check your nvcc compiler.

**Comment by lcl-git-3d** [comment]
Thank you for your reply！I have checked my nvcc compiler,but I don't know what the problem is.Could you take a look at it for me, please? Thank you very much indeed！
![1685703861337](https://github.com/princeton-vl/Coupled-Iterative-Refinement/assets/125371176/d7677295-5be8-407f-be34-031f1206bbfb)
![1685703861343](https://github.com/princeton-vl/Coupled-Iterative-Refinement/assets/125371176/8850637c-6e38-4cb1-84f4-08f11faed7e2)
![1685703862421](https://github.com/princeton-vl/Coupled-Iterative-Refinement/assets/125371176/0147f2ac-cc35-4c63-bee9-ddc9680000d4)
When I checked the ncvv compiler, I found that the cuda version is 11.3, while the cuda version installed in my virtual environment according to Environment. yaml is 11.1. Is this the problem?

**Comment by rahul-martianaut** [comment]
Hello @lcl-git-3d  . How did you solve this issue? I got the same error
