### ISSUE TITLE
Library version - lietorch

### ISSUE THREAD

**Issue by ji-min-song** [princeton-vl/Coupled-Iterative-Refinement#4]
Hello, Thank you for the good research and git hub repo.

We use your code for object pose estimation research with lietorch=0.2 from early this year.
But we can't set up conda env with lietorch=0.2, and lietorch's version is available only 0.4 now. 
This may not be a real problem. Can you check this problem?

**Comment by lahavlipson** [comment]
I don't expect this will cause any problems. If there are errors, please feel free to post them here and I will try to help.

**Comment by ji-min-song** [comment]
![캡처](https://user-images.githubusercontent.com/80804530/190884657-c38f28ab-3064-435a-aaa8-2d129e0a1f6b.PNG)

I am experiencing a simple conda conflict..............

**Comment by lahavlipson** [comment]
What nvidia gpu are you using? I can't reproduce this issue so more information would help.

**Comment by ji-min-song** [comment]
I'm using GeForce RTX 3090 now.
This looks like a library version conflict, can you check if the environment is well organized with the current environment.yaml?

**Comment by lahavlipson** [comment]
The environment.yaml seems fine, it is pretty under-specified. You may have better luck installing the packages one-by-one since there aren't that many, which should identify the problematic one.

What conda version are you using? I am using `conda 4.14.0`

**Comment by ji-min-song** [comment]
I am using conda 4.14.0 too

![캡처111](https://user-images.githubusercontent.com/80804530/191386952-8f4cc91c-62d7-4719-8edc-3d5daa65c6c7.PNG)

**Comment by ji-min-song** [comment]
This problem is solved. 
I had to check my nvcc compiler for `lietorch`
