### ISSUE TITLE
Detector training pipeling

### ISSUE THREAD

**Issue by Basilel7** [princeton-vl/Coupled-Iterative-Refinement#7]
Hello, Thanks for sharing your great work.

I wanted to know if you had a training pipeline for the MaskRCNN-detector in order to train the model on a custom dataset ?

Thanks

**Comment by lahavlipson** [comment]
We use the pre-trained MaskRCNN weights from [CosyPose](https://github.com/ylabbe/cosypose). The instructions for running their training pipeline are at the very bottom of their README: https://github.com/ylabbe/cosypose/blob/c90a04f434b1e89f02341cc03899eb63ea8facba/README.md#detection
